apiVersion: v1
kind: Service
metadata:
    name: "web-app"
    labels:
    app: web-app
spec:
    type: LoadBalancer
    selector:
    app: 
    ports:
    - port: 80
        targetPort: 80
        nodePort: 8086
        protocol: TCP